javac "Main.java"
javac "View.java"
javac "Controller.java"
javac "Model.java"
javac "Player.java"
javac "PlayerPanel.java"
javac "splash.java"
javac "udpServer.java"
javac "Audio.java"
java -cp .:postgresql-42.7.4.jar "Main"